// <auto-generated />
namespace Supermarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class for_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(for_test));
        
        string IMigrationMetadata.Id
        {
            get { return "202210170815068_for_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
