// <auto-generated />
namespace Supermarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Casher_Admin2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Casher_Admin2));
        
        string IMigrationMetadata.Id
        {
            get { return "202210170652458_Casher_Admin2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
